package com.example.radiology.domain;

public enum MedicalImagingType {
	CXR, CT, MRI, ULTRASOUND, PET, SPECT, X_RAY, FLUOROSCOPY, MAMMOGRAPHY, DEXA_SCAN, ANGIOGRAPHY, ECHOCARDIOGRAPHY,
	THERMOGRAPHY, ENDOSCOPY, CAPSULE_ENDOSCOPY, OCT, DTI, FUSION_IMAGING, INTERVENTIONAL_RADIOLOGY;
}
